require:
  - rubocop-katalyst

AllCops:
  TargetRubyVersion: 3.2.0
  Exclude:
    # Dummy app
    - spec/dummy/*
    - spec/dummy/bin/*
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*
    - spec/dummy/deploy/*
    - spec/dummy/node_modules/**/*
    - spec/dummy/vendor/bundle/**/*

Rails/ApplicationController:
  Exclude:
    - app/controllers/katalyst/navigation/base_controller.rb
